### ISSUE TITLE
proteoid root

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#588]
Request from collaborators at New Phytologist:
Proteoid root(s), also known as cluster roots isn't in the PO at present, almost certainly because although the PO now covers a wide range of plant types, proteoid roots are specific to one family of plants, the Proteaceae of the Southern Hemisphere. 

Reported by: cooperl09

Original Ticket: [obo/plant-ontology-po-term-requests/588](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/588)

**Comment by austinmeier** [comment]
Added term:  proteoid root (PO:0000067) with def'n: A root (PO:0009005) from any species that forms one or more clusters along its length. A cluster has closely spaced lateral roots (PO:0020121) of limited growth. And xref: PO_GIT:588, related synonyms: root cluster, and cluster root.

**Comment by cooperl09** [comment]
Looks good, please include comment and parent.
    
    On 8/11/15 3:21 PM, austinmeier wrote:
    
    
      Added term: proteoid root (PO:0000067) with def'n: A root
        (PO:0009005) from any species that forms one or more clusters
        along its length. A cluster has closely spaced lateral roots
        (PO:0020121) of limited growth. And xref: PO_GIT:588, related
        synonyms: root cluster, and cluster root.
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
**********************************************************
Laurel (Lol) Cooper, PhD
Bioinformatics Scientist, The Planteome Project 
Dept. of Botany and Plant Pathology
Rm 3086, Cordley Hall
Oregon State University
Corvallis, OR 97331
Web: www.planteome.org

Phone: 541-737-5272
Fax: 541-737-3573
Skype: cooperlol910
***********************************************************

**Comment by austinmeier** [comment]
term: proteoid root (PO:0000067),
is_a root (PO:0009005)
comment:  The terms proteoid root, cluster root, and root cluster have all been used in the literature to describe either the proteoid root axis or clusters of rootlets, and caution should be taken when comparing studies because the definitions of these terms vary.-from Watts and Evans, (Plant Physiology,1999)
DBXref: PMID:10517822
synonyms: cluster root, and root cluster (both related)

**Comment by cooperl09** [comment]
Slightly modified def'n and comment:  
proteoid root (PO:0000067): A root (PO:0009005) that forms one or more clusters of closely spaced lateral roots (PO:0020121) of limited growth along its length.

Comment: The terms proteoid root, cluster root, and root cluster have all been used in the literature to describe either the proteoid root axis or clusters of rootlets, and caution should be taken when comparing studies because the definitions of these terms vary (Watts and Evans, 1999; Plant Physiology).
