### ISSUE TITLE
plant embryo cotyledon

### ISSUE THREAD

**Issue by jaiswalp** [Planteome/plant-ontology#621]
http://dev.planteome.org/amigo/term/PO:0020030#display-lineage-tab
and
http://dev.planteome.org/amigo/term/PO:0025470#display-lineage-tab

My understanding is that there is only one instance of cotyledon, that is in seed. It's the same one that appears in the seedling after germination. We have another sibling of this term 'seedling cotyletodon'. It's funny, but I can live with it.

However, I suggest renaming the PO:0025470 to 'seed cotyledon'

I have never heard of 'embryo cotyledon'. These are two separate plant structures.

**Comment by maxglycine** [comment]
I think that “seed cotyledon” should be a stage in the development of a cotyledon.  This comes into play when people dissect out cotyledons or cotyledon tissues and then do expression studies on the whole cotyledon or cotyledonary tissues.


On Jan 7, 2016, at 12:11 AM, Common Reference Ontologies for Plants <notifications@github.com<mailto:notifications@github.com>> wrote:


http://devplanteomeorg/amigo/term/PO:0020030#display-lineage-tab
and
http://devplanteomeorg/amigo/term/PO:0025470#display-lineage-tab

My understanding is that there is only one instance of cotyledon, that is in seed It's the same one that appears in the seedling after germination We have another sibling of this term 'seedling cotyletodon' It's funny, but I can live with it

However, I suggest renaming the PO:0025470 to 'seed cotyledon'

I have never heard of 'embryo cotyledon' These are two separate plant structures

—
Reply to this email directly or view it on GitHub<https://github.com/Planteome/plant-ontology/issues/621>.

Rex Nelson
Computational Biologist
G329 Agronomy Hall
Iowa State University
Ames, IA 50011
nelsonrt@iastate.edu<mailto:nelsonrt@iastate.edu>
515-294-1297

"Time flies like an arrow. Fruit flies like a banana"

**Comment by ramonawalls** [comment]
A single instance of a cotyledon goes through stages of development during which it is first part of an embryo (i.e. the seed has not yet germinated) and later part of a seedling (i.e. after germination). It is the same cotyledon, but at two different points in time, with different sets of characteristics based on its development. The reason we have two classes for this is as a convenience, because (as @maxglycine pointed out) people do experiments where they are sampling cotyledons at these different stages. 

I think we should stick with the existing names, because they clearly reflect the definitions of the structures:

PO:0025471: A cotyledon (PO:0020030) that is part of a whole plant (PO:0000003) in the seedling development stage (PO:0007131).

PO:0025471: A cotyledon (PO:0020030) that is part of a plant embryo (PO:0009009).

Note that the slight differences in the definitions are because we have a precomposed term for plant embryo (=whole plant in the embryo development stage) but not for seedling.

Naming PO:0025471 'seed cotyledon' implies that it is part of the seed, which it is, but that relationship is less direct than than being part of the embryo.

My suggestion is to keep the names as is and add "seed cotyledon" as an exact synonym for "embryo cotyledon".

**Comment by jaiswalp** [comment]
I agree with Ramona

**Comment by cooperl09** [comment]
Great, closing this ticket

**Comment by jaiswalp** [comment]
as @ramonawalls  suggested ...add "seed cotyledon" as an exact synonym for "embryo cotyledon".

**Comment by cooperl09** [comment]
Suggest the scope should be **narrow,** as the PO definition of plant embryo encompasses embryos not from seeds.

**Comment by ramonawalls** [comment]
I was thinking exact, because even though embryos encompass non-seed plants, only seed plant have cotyledons. I don't have strong feelings about the scope of the synonym though.

**Comment by cooperl09** [comment]
Actually, I was thinking of embryos which don't come from seeds, even though they are from seed plants, such as those created through tissue culture of microspores or somatic cells.

**Comment by ramonawalls** [comment]
Good point!

Enviado de Baja Arizona.
